using System.Text.Json.Serialization;

namespace AlarmClock.Core.Model;

/// <summary>How much an alarm may intrude. Each level resolves to a full profile. | O quanto um alarme pode atrapalhar. Cada nível resolve para um perfil completo.</summary>
public enum UrgencyLevel
{
    /// <summary>Silent toast; passes and disappears. | Toast silencioso; passa e some.</summary>
    Whisper,

    /// <summary>Corner card with one beep; the default. | Card no canto com um toque; o padrão.</summary>
    Normal,

    /// <summary>Centered window that doesn't dismiss itself. | Janela central que não sai sozinha.</summary>
    High,

    /// <summary>Full screen on every monitor; needs a deliberate action. | Tela cheia em todos os monitores; exige ação deliberada.</summary>
    Critical,
}

/// <summary>Which kind of window the alert uses. | Que tipo de janela o alerta usa.</summary>
public enum PresentationMode
{
    /// <summary>Native Windows toast (subject to Focus Assist). | Toast nativo do Windows (sujeito ao Assistente de Foco).</summary>
    Toast,

    /// <summary>Own card in the screen corner. | Card próprio no canto da tela.</summary>
    Corner,

    /// <summary>Centered, topmost window. | Janela centralizada, topmost.</summary>
    Modal,

    /// <summary>Full-screen overlay on every monitor. | Overlay em tela cheia, em todos os monitores.</summary>
    Fullscreen,
}

/// <summary>What the user must do to dismiss the alert. | O que o usuário precisa fazer para dispensar o alerta.</summary>
public enum DismissMode
{
    /// <summary>Disappears on its own. | Some sozinho.</summary>
    Auto,

    /// <summary>One click. | Um clique.</summary>
    Click,

    /// <summary>Hold the button for a few seconds. | Segurar o botão por alguns segundos.</summary>
    HoldButton,

    /// <summary>Type a phrase. | Digitar uma frase.</summary>
    TypePhrase,
}

/// <summary>What to do with an alarm that fired while the PC slept or you were away. | O que fazer com um alarme que disparou com o PC dormindo ou você ausente.</summary>
public enum MissedAlarmBehavior
{
    /// <summary>Forget it. | Esquece.</summary>
    Discard,

    /// <summary>Keep it and show as "missed" on return. | Guarda e mostra como "perdido" ao voltar.</summary>
    ShowOnReturn,

    /// <summary>Actually fire on return. | Dispara de verdade ao voltar.</summary>
    FireOnReturn,
}

/// <summary>How the alert sounds. Without <see cref="FilePath"/>, a tone is synthesized. | Como o alerta soa. Sem <see cref="FilePath"/>, um tom é sintetizado.</summary>
public sealed record SoundSpec
{
    /// <summary>A silent spec. | Uma especificação silenciosa.</summary>
    public static SoundSpec Silent { get; } = new() { IsSilent = true };

    /// <summary>Whether no sound plays. | Se nenhum som toca.</summary>
    public bool IsSilent { get; init; }

    /// <summary>User audio file. Null = tone generated by the app. | Arquivo de áudio do usuário. Nulo = tom gerado pelo app.</summary>
    public string? FilePath { get; init; }

    /// <summary>Volume, 0..1. | Volume, 0..1.</summary>
    public double Volume { get; init; } = 0.7;

    /// <summary>Plays until the alert is dismissed. | Toca até o alerta ser dispensado.</summary>
    public bool Loop { get; init; }

    /// <summary>Gap between repeats. <see cref="TimeSpan.Zero"/> = play once. | Intervalo entre repetições. <see cref="TimeSpan.Zero"/> = toca uma vez.</summary>
    public TimeSpan RepeatEvery { get; init; }

    /// <summary>Ramps the volume up gradually. | Sobe o volume gradualmente.</summary>
    public TimeSpan FadeIn { get; init; }
}

/// <summary>How much an alarm can be pushed back, and how many times. | Quanto o alarme pode ser adiado, e quantas vezes.</summary>
public sealed record SnoozePolicy
{
    /// <summary>No snoozing allowed. | Adiamento não permitido.</summary>
    public static SnoozePolicy None { get; } = new() { Options = [], MaxCount = 0 };

    /// <summary>Offered snooze durations. | Durações de adiamento oferecidas.</summary>
    public required IReadOnlyList<TimeSpan> Options { get; init; }

    /// <summary>How many consecutive snoozes are allowed. | Quantos adiamentos seguidos são permitidos.</summary>
    public required int MaxCount { get; init; }

    /// <summary>Whether snoozing is possible at all. | Se é possível adiar.</summary>
    [JsonIgnore]
    public bool IsEnabled => MaxCount > 0 && Options.Count > 0;

    /// <summary>Default snooze duration. | Duração de adiamento padrão.</summary>
    [JsonIgnore]
    public TimeSpan DefaultOption => Options.Count > 0 ? Options[0] : TimeSpan.FromMinutes(5);
}

/// <summary>
/// The full definition of an urgency level: presentation, sound, dismissal and snooze. | A definição completa de um nível de urgência: apresentação, som, dispensa e adiamento.
/// </summary>
public sealed record UrgencyProfile
{
    /// <summary>Which level this profile is for. | A qual nível este perfil pertence.</summary>
    public required UrgencyLevel Level { get; init; }

    /// <summary>How the alert is shown. | Como o alerta é mostrado.</summary>
    public required PresentationMode Presentation { get; init; }

    /// <summary>How it sounds. | Como soa.</summary>
    public required SoundSpec Sound { get; init; }

    /// <summary>Null = the alert stays until the user acts. | Nulo = o alerta fica até o usuário agir.</summary>
    public TimeSpan? AutoDismissAfter { get; init; }

    /// <summary>How it is dismissed. | Como é dispensado.</summary>
    public required DismissMode Dismiss { get; init; }

    /// <summary>Snooze rules. | Regras de adiamento.</summary>
    public required SnoozePolicy Snooze { get; init; }

    /// <summary>What happens when fired while away. | O que acontece quando dispara com você ausente.</summary>
    public required MissedAlarmBehavior WhenAway { get; init; }

    /// <summary>Phrase required for <see cref="DismissMode.TypePhrase"/>. | Frase exigida por <see cref="DismissMode.TypePhrase"/>.</summary>
    public string DismissPhrase { get; init; } = "acordei";
}

/// <summary>The four level presets. | Os quatro presets de nível.</summary>
public static class UrgencyProfiles
{
    private static readonly Dictionary<UrgencyLevel, UrgencyProfile> Presets = new()
    {
        [UrgencyLevel.Whisper] = new UrgencyProfile
        {
            Level = UrgencyLevel.Whisper,
            Presentation = PresentationMode.Toast,
            Sound = SoundSpec.Silent,
            AutoDismissAfter = TimeSpan.FromSeconds(7),
            Dismiss = DismissMode.Auto,
            Snooze = SnoozePolicy.None,
            WhenAway = MissedAlarmBehavior.Discard,
        },

        [UrgencyLevel.Normal] = new UrgencyProfile
        {
            Level = UrgencyLevel.Normal,
            Presentation = PresentationMode.Corner,
            Sound = new SoundSpec { Volume = 0.5 },
            AutoDismissAfter = TimeSpan.FromSeconds(30),
            Dismiss = DismissMode.Click,
            Snooze = new SnoozePolicy
            {
                Options = [TimeSpan.FromMinutes(5), TimeSpan.FromMinutes(10), TimeSpan.FromMinutes(15)],
                MaxCount = int.MaxValue,
            },
            WhenAway = MissedAlarmBehavior.ShowOnReturn,
        },

        [UrgencyLevel.High] = new UrgencyProfile
        {
            Level = UrgencyLevel.High,
            Presentation = PresentationMode.Modal,
            Sound = new SoundSpec { Volume = 0.7, RepeatEvery = TimeSpan.FromSeconds(10) },
            AutoDismissAfter = null,
            Dismiss = DismissMode.Click,
            Snooze = new SnoozePolicy { Options = [TimeSpan.FromMinutes(5)], MaxCount = 3 },
            WhenAway = MissedAlarmBehavior.ShowOnReturn,
        },

        [UrgencyLevel.Critical] = new UrgencyProfile
        {
            Level = UrgencyLevel.Critical,
            Presentation = PresentationMode.Fullscreen,
            Sound = new SoundSpec { Volume = 1.0, Loop = true, FadeIn = TimeSpan.FromSeconds(5) },
            AutoDismissAfter = null,
            Dismiss = DismissMode.HoldButton,
            Snooze = new SnoozePolicy { Options = [TimeSpan.FromMinutes(2)], MaxCount = 1 },
            WhenAway = MissedAlarmBehavior.FireOnReturn,
        },
    };

    /// <summary>Profile for a level. | Perfil de um nível.</summary>
    public static UrgencyProfile Get(UrgencyLevel level) => Presets[level];

    /// <summary>All profiles. | Todos os perfis.</summary>
    public static IEnumerable<UrgencyProfile> All => Presets.Values;
}
